image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
  - name: Prepare deps
    init: -A:test -P
  - name: Clover Config
    command: cp .clover/config.cljs ~/.config/clover/
  - name: Start REPL
    command: clojure -J-Dclojure.server.repl="{:address \"0.0.0.0\" :port 50505 :accept clojure.core.server/repl}" -A:test
  - name: Start up
    command: code CHANGELOG.md

github:
  prebuilds:
    main: true